### ISSUE TITLE
Re-add support for RcppRedis

### ISSUE THREAD

**Issue by drknexus** [ropensci/RedisAPI#7]
I notice that support for RcppRedis went away recently.  Was it just a matter of convenience or are there now things that RedisAPI needs out of a connection object that RcppRedis doesn't offer?

**Comment by richfitz** [comment]
Support for RcppRedis went away because I changed my mind about which order the packages should work; rather than this package providing the glue for various packages it provides the hooks and the packages import this package.  This is in preparation for starting to move this into CRAN without dependencies such as [rrlite](https://github.com/ropensci/rrlite) that don't yet build on Windows.

I'll talk with Dirk about including support in RedisAPI and if that fits with his plans for the package that could happen.  Otherwise it could be spun out into another package the imports both RcppRedis and RedisAPI very easily.  The main issue would be subscribe and pipeline support, which would require C++ level support in RcppRedis, too.

**Comment by drknexus** [comment]
Does RedisAPI actually require subscribe and pipeline to be working or could we just create stubs that throw an error and identify that the feature isn't available through RcppRedis (yet)? I'm trying to determine the minimal viable path forward.

**Comment by richfitz** [comment]
There was support [here](https://github.com/ropensci/RedisAPI/blob/42102f95e1662502e012952b7c9ec3901ca178a4/R/redis_util.R#L36-L48) for adding the stubs automatically.  Perhaps worth adding that back as it's also an issue for pipelining.

The other issue is that RedisAPI generates commands that are in a different format than expected by RcppRedis; the list structure needs removing and errors need to be thrown if any raw vectors (from binary serialisation) are present.  I think that's why I moved it out of the way for now.

**Comment by drknexus** [comment]
Alternatively, RcppRedis.might be able to expose a list consuming back-end
to supplement execv.  It looks like GPL licenses can in principle include
two clause BSD code.  I can't speak for Dirk, but are you open to me
looking at redux in expanding my understanding and trying to make RcppRedis
support RedisAPI?  Open to borrowing and modification of functions?

**Comment by richfitz** [comment]
Here is a possible RcppRedis driver for RedisAPI.  It handles everything except for pipelining, subscribe and binary serialisation (despite the actual RcppRedis doing a nice job of serialisation for the functions that exposes).

```r
rcppredis_connection <- function(config=RedisAPI::redis_config()) {
  connect <- function(config) {
    new(RcppRedis::Redis, config$host, config$port)$execv
  }
  stop_if_raw <- function(x) {
    if (any(vapply(x, is.raw, logical(1)))) {
      stop("Binary objects not supported through RedisAPI + RcppRedis")
    }
  }
  run_command <- function(r, cmd) {
    ## Not 100% sure this will always work, but should deal with the
    ## non binary serialisation cases pretty well I think.
    ##
    ## Treatment of TRUE/FALSE is different as redux will store them
    ## as 1/0 but this will store them as "TRUE"/"FALSE".
    ##
    ## RcppRedis returns different values to redux in a few places
    ## (most obviously redis status, but integer treatment differs
    ## too).
    stop_if_raw(cmd)
    if (any(vapply(cmd, is.list, logical(1)))) {
      cmd <- unlist(cmd, FALSE)
      stop_if_raw(cmd)
    }
    r(as.character(unlist(cmd)))
  }
  r <- connect(config)
  ret <-
    list(
      config=function() {
        config
      },
      reconnect=function() {
        r <<- connect(config)
      },
      command=function(cmd) {
        run_command(r, cmd)
      },
      ## Stubs for unsupported functions.
      pipeline=function(...) {
        stop("Pipelining not supported with RcppRedis")
      },
      subscribe=function(...) {
        stop("Subscription not supported with RcppRedis")
      })
}
```

Minimal test case that works with both CRAN and github RcppRedis.

```r
con <- redis_api(rcppredis_connection())
con$SET("foo:bar", 100)
con$SET("foo:baz", 1000)
con$SCAN(0, MATCH="foo:*", COUNT=100)
RedisAPI::scan_find(con, "foo:*")
con$GET("foo:bar")
```

You're welcome to do whatever you like with RcppRedis and RedisAPI, though I would wager that until RedisAPI is on CRAN Dirk will be reluctant to take anything -- CRAN packages can't have non-CRAN dependencies, and I don't exactly have the best track record of putting things up on CRAN.

I'm reworking the vignettes for this package at the moment and it may hit CRAN before the end of the year, depending on travel .

**Comment by eddelbuettel** [comment]
With the [drat](http://cran.rstudio.com/package=drat) experience, I am certain we can have `Suggests:` to packages outside of CRAN but in a repo.  `Depends:` and `Imports:` are as far as I know excluded from that avenue...   So with that thumbs-up towards CRANification.

**Comment by richfitz** [comment]
Added in 8b019153e19f883002626a50ee7281f864031dcc
